version: '39'
services:
  app:
    container_name: 'app'
    image: node:alpine
    volumes:
      - ./wilayah-nusantara:/app/
      - node_modules:/app/node_modules
    ports:
      - "1945:1945"
    stdin_open: true
    command: 
        - /bin/sh
        - -c
        - |
            cd app
            npm install -g pnpm
            pnpm install
            pnpm mikro-orm migration:up -w
            pnpm dev
    depends_on:
      - db_mysql
  
  db_mysql:
    image: mysql:oraclelinux8
    restart: always
    environment:
      MYSQL_DATABASE: 'nusantara-api'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  web:
    image: php:7.2.5-apache
    container_name: php7.2.5-apache
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html/
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli 
          echo "extension installed.....starting php-fpm........................................"
          php-fpm
          a2enmod rewrite
          apache2-foreground
    depends_on:
      - db
      - db_mysql
  
  db:
    image: mariadb:10.6
    container_name: mariadb10.6
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE_FILE: /run/secrets/db_database
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3307:3306"
    volumes:
      - my_mariadb:/var/lib/mysql
    secrets:
      - db_database
      - db_password
      - db_root_password
      - db_user

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_mysql

volumes:
  node_modules:
  my-db:
  my_mariadb:
      
secrets:
  db_database:
    file: db_database.txt
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  db_user:
    file: db_user.txt


