version: '39'
services:
  web:
    image: php:7.2.5-apache
    container_name: php7.2.5-apache
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html/
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli 
          echo "extension installed.....starting php-fpm........................................"
          php-fpm
          a2enmod rewrite
          apache2-foreground
    depends_on:
      - db
  
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: /run/secrets/db_database
      MYSQL_USER: /run/secrets/db_user
      MYSQL_PASSWORD: /run/secrets/db_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    secrets:
      - db_database
      - db_password
      - db_root_password
      - db_user

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
secrets:
  db_database:
    file: db_database.txt
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  db_user:
    file: db_user.txt


